[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "croco-web3-utils"
version = "0.1.0"
authors = [
    { name = "Alexey", email = "abelenkov2006@gmail.com" },
]
description = "The package containing utilities to develop Web3-based projects"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    'Development Status :: 1 - Planning',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3 :: Only',
    'License :: OSI Approved :: Apache Software License',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: MacOS'
]

[project.urls]
source = "https://github.com/blnkoff/croco-web3-utils"
